pipeline{
    agent any
        stages{
            stage('In stage 1'){
                steps{
                    echo "Stage- 1 finished"
                }
                
            }
            
            stage("In stage 2"){
                steps{
                    echo "stage 2 finished"
                }
            }
        }
    
}